name: techblog
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.0-87.0.dev <4.0.0'

dependencies:
  cached_network_image: ^3.3.0
  cupertino_icons: ^1.0.6
  dio: ^5.3.4
  file_picker: ^6.1.1
  flutter:
    sdk: flutter
  flutter_gen: ^5.3.2
  flutter_spinkit: ^5.2.0
  flutter_svg: ^2.0.9
  flutter_widget_from_html: ^0.14.7
  get: ^4.6.6
  get_storage: ^2.1.1
  percent_indicator: ^4.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0


flutter_gen:
  output: lib/gen/ # Optional (default: lib/gen/)
  line_length: 80 # Optional (default: 80)

  # Optional
  integrations:
    flutter_svg: true
    flare_flutter: true
    rive: true
    lottie: true

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/

  fonts:
    - family: Dana
      fonts:
        - asset: assets/fonts/Dana-Thin.ttf
          weight: 100
        - asset: assets/fonts/Dana-UltraLight.ttf
          weight: 200
        - asset: assets/fonts/Dana-Light.ttf
          weight: 300
        - asset: assets/fonts/Dana-Regular.ttf
          weight: 400
        - asset: assets/fonts/Dana-Medium.ttf
          weight: 500
        - asset: assets/fonts/Dana-DemiBold.ttf
          weight: 600
        - asset: assets/fonts/Dana-Bold.ttf
          weight: 700
        - asset: assets/fonts/Dana-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Dana-Fat.ttf
          weight: 900